events{}

http {

#upstream block 

#Nginx send request to web service on port 5002, we are gonna call this group "backend"
upstream backend { 
    server web:5002;
}


#server block

#ngix listens on port 80 internally, send all traffic to backend (which is defined in the upstream block)
server {
    listen 5002;
    location / {
        proxy_pass http://backend; 
        }
   }
}
