services: 
   web:  
    build: ./flask 
    expose:
       - "5002"
    environment:
     REDIS_HOST: 'redis' 
     REDIS_PORT: 6379
     REDIS_DB: 0
    
   


   redis:
    build: ./redis 
    volumes:
     - redis_storage:/data 


   reverse-proxy-nginx:
    image: nginx:1.23
    ports:
       - "5002:5002"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
       - web



volumes:         
   redis_storage:
    

 